In [1]:
from xgboost import XGBRegressor
from xgboost import plot_importance, plot_tree

from sklearn.datasets import fetch_california_housing # dataset
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [4]:
housing = fetch_california_housing()
X = housing.data
y = housing.target
col_names = housing.feature_names

In [7]:
print(X.shape)
print(X)
print(y.shape)
print(y[:10])
print(y[-10:])

(20640, 8)
[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]
(20640,)
[4.526 3.585 3.521 3.413 3.422 2.697 2.992 2.414 2.267 2.611]
[1.12  1.072 1.156 0.983 1.168 0.781 0.771 0.923 0.847 0.894]


In [8]:
type(X), type(y)

(numpy.ndarray, numpy.ndarray)

In [11]:
import numpy as np
y.mean()

2.068558169089147

In [12]:
y = np.log(y)
y.mean()

0.5719587205516943

In [13]:
y[:10]

array([1.50983855, 1.27675847, 1.25874504, 1.22759167, 1.23022518,
       0.99214004, 1.09594206, 0.88128512, 0.81845737, 0.95973329])

In [15]:
import pandas as pd

X_df = pd.DataFrame(X, columns=col_names)
X_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

# train_test_split - test_size 생략시, 75:25 가 default

In [17]:
x_train, x_test, y_train, y_test = train_test_split(X_df, y) # test_size = 0.25
x_train.shape 
type(x_train) 

pandas.core.frame.DataFrame

In [18]:
y_train.shape 
type(y_train) 

numpy.ndarray

In [ ]:
model = 